<<<<<<< HEAD
services:
  - type: web
    name: skycrm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
=======
services:
  - type: web
    name: skycrm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
>>>>>>> c4fbf1a242e26ed4913c23b5d9f20b11455a3c29
        sync: false # Will be set to backend URL manually in Render dashboard